# H2のインメモリDBを使用する。
# アプリを終了するとDBの内容は消える。
spring.datasource.url=jdbc:h2:mem:tododb

# H2のJDBCドライバ。
spring.datasource.driver-class-name=org.h2.Driver

# H2接続用ユーザー。
spring.datasource.username=sa

# 今回はパスワードを使用しない。
spring.datasource.password=

# Entityの定義から起動時にテーブルを作り、
# アプリ終了時に削除する。
spring.jpa.hibernate.ddl-auto=create-drop

# Hibernateによるテーブル作成後にdata.sqlを実行する。
spring.jpa.defer-datasource-initialization=true

# data.sqlによる初期データ投入を有効にする。
spring.sql.init.mode=always
